edition = "2018"

# Provides consistent and reliable application
use_small_heuristics = "Max"
fn_single_line = true # Only because it's consistent with the above

# For consistency
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true

# SHOULD be less than this, MUST be less than 100
max_width = 80

# Preference
newline_style = "Unix"

# Automatic help
normalize_doc_attributes = true
normalize_comments = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
